name: 'Mainline Diff'
description: 'Diff output of script on PR versus target branch.'
inputs:
  file-to-execute:
    description: 'File to execute to produce data to diff'
    required: true
  files-to-clobber:
    description: 'Files from this branch to overwrite on ancestor'
    required: false
    default: ''
  file-to-image-diff:
    description: 'Filepath output from executing target containing an image to diff. If defined, supersedes stdout.'
    required: false
    default: ''
  file-to-pdf-diff:
    description: 'Filepath output from executing target containing a PDF to diff. If defined, supersedes stdout.'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: "Checkout full repo"
      uses: actions/checkout@v3
      with:
         fetch-depth: 0

    - name: Install ghostscript
      run: sudo apt install ghostscript
      shell: bash

    - name: Change ImageMagick security policy
      run: |
        DQT='"' 
        SRC="rights=${DQT}none${DQT} pattern=${DQT}PDF${DQT}"
        RPL="rights=${DQT}read\|write${DQT} pattern=${DQT}PDF${DQT}"
        sudo sed -i "s/$SRC/$RPL/" /etc/ImageMagick-6/policy.xml
      shell: bash

    - name: "Backup clobbering files"
      run: |
        while IFS= read -r file; do
          mkdir -p $(dirname "/tmp/diff-test-clobbering/${file}") 
          cp "${file}" "/tmp/diff-test-clobbering/${file}" 
        done <<< "${{ inputs.files-to-clobber }}"
      shell: bash

    # This PR ref is "$GITHUB_SHA", representing merge of PR into target.
    # Target is ${{ github.event.pull_request.base.ref }}.
    - name: "Run on this PR"
      run: |
        echo 'DIFF_PR_OUTPUT<<EOF' >> $GITHUB_ENV
        "${{inputs.file-to-execute}}" | tee -a $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
      shell: bash

    - name: "Backup image output"
      if: "${{ inputs.file-to-image-diff }}"
      run: cp "${{ inputs.file-to-image-diff }}" /tmp/diff-test-image-pr
      shell: bash

    - name: "Upload image output"
      if: "${{ inputs.file-to-image-diff }}"
      uses: actions/upload-artifact@v1.0.0
      with:
        name: pr-output
        path: "${{ inputs.file-to-image-diff }}"

    - name: "Backup pdf output"
      if: "${{  inputs.file-to-pdf-diff }}"
      run: cp "${{ inputs.file-to-pdf-diff }}" /tmp/diff-test-pdf-pr
      shell: bash

    - name: "Upload pdf output"
      if: "${{ inputs.file-to-pdf-diff }}"
      uses: actions/upload-artifact@v1.0.0
      with:
        name: pr-output
        path: "${{ inputs.file-to-pdf-diff }}"

    - name : "Checkout target"
      run: |
        git checkout "${{ github.event.pull_request.base.ref }}"
      shell: bash

    - name: "Restore clobbering files"
      run: |
        while IFS= read -r file; do
          cp "/tmp/diff-test-clobbering/${file}" "${file}" 
        done <<< "${{ inputs.files-to-clobber }}"
      shell: bash

    - name: "Run on target"
      run: |
        echo 'DIFF_TARGET_OUTPUT<<EOF' >> $GITHUB_ENV
        "${{inputs.file-to-execute}}" | tee -a $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
      shell: bash

    - name: "Upload image output"
      if: "${{ inputs.file-to-image-diff }}"
      uses: actions/upload-artifact@v1.0.0
      with:
        name: target-output
        path: "${{ inputs.file-to-image-diff }}"

    - name: "Upload pdf output"
      if: "${{ inputs.file-to-pdf-diff }}"
      uses: actions/upload-artifact@v1.0.0
      with:
        name: target-output
        path: "${{ inputs.file-to-pdf-diff }}"

    - name: "Diff stdout outputs"
      if: "${{ ! inputs.file-to-image-diff && ! inputs.file-to-pdf-diff }}"
      run: 'diff <(echo "$DIFF_PR_OUTPUT") <(echo "$DIFF_TARGET_OUTPUT") | tee diff-output || true'
      shell: bash

    - name: "Upload stdout diff"
      if: "${{ ! inputs.file-to-image-diff && ! inputs.file-to-pdf-diff }}"
      uses: actions/upload-artifact@v1.0.0
      with:
        name: diff-output
        path: diff-output

    - name: "Add stdout diff comment"
      if: "${{ ! inputs.file-to-image-diff && ! inputs.file-to-pdf-diff }}"
      run: |
        DIFF_CONTENTS="$(cat diff-output)"
        [[ ! -z "$DIFF_CONTENTS" ]] && \
        jq -nc "{\"body\": \"\`\`\`\n$DIFF_CONTENTS\n\`\`\`\"}" | \
        curl -sL  -X POST -d @- \
          -H "Content-Type: application/json" \
          -H "Authorization: token ${{ github.token }}" \
          "${{ github.event.pull_request.comments_url }}"
      shell: bash

    - name: "Diff image outputs"
      if: "${{ inputs.file-to-image-diff }}"
      run: |
        compare /tmp/diff-test-image-pr "${{ inputs.file-to-image-diff }}" -subimage-search -dissimilarity-threshold 1 /tmp/diff-result.png || return_code=$?
        # imagemagick requires first image to be larger. Just try both!
        if [ "${return_code}" -eq 2 ]; then
          compare "${{ inputs.file-to-image-diff }}" /tmp/diff-test-image-pr -subimage-search -dissimilarity-threshold 1 /tmp/diff-result.png || return_code=$?
        fi
        echo "IMAGE_DIFF_STATUS=$return_code" >> $GITHUB_ENV
      shell: bash
  
    - name: "Upload image diff"
      if: "${{ inputs.file-to-image-diff }}"
      uses: actions/upload-artifact@v1.0.0
      with:
        name: diff-output
        path: /tmp/diff-result.png

    - name: "Add image diff comment"
      if: "${{ inputs.file-to-image-diff }}"
      run: |
        if [ "$IMAGE_DIFF_STATUS" -eq 0 ]; then
          MESSAGE="No image diff."
        else
          MESSAGE="Image diff. See artifacts for file."          
        fi

        jq -nc "{\"body\": \"$MESSAGE\"}" | \
        curl -sL  -X POST -d @- \
          -H "Content-Type: application/json" \
          -H "Authorization: token ${{ github.token }}" \
          "${{ github.event.pull_request.comments_url }}"
      shell: bash

    - name: "Diff pdf outputs"
      if: "${{ inputs.file-to-pdf-diff }}"
      run: |
        convert -append /tmp/diff-test-pdf-pr /tmp/diff-test-pdf-pr.png
        convert -append "${{ inputs.file-to-pdf-diff }}" /tmp/diff-test-pdf-target.png
        compare /tmp/diff-test-pdf-pr.png /tmp/diff-test-pdf-target.png -subimage-search -dissimilarity-threshold 1 /tmp/diff-result-pdf.png || return_code=$?
        # imagemagick requires first image to be larger. Just try both!
        if [ "${return_code}" -eq 2 ]; then
          compare /tmp/diff-test-pdf-target.png /tmp/diff-test-pdf-pr.png -subimage-search -dissimilarity-threshold 1 /tmp/diff-result-pdf.png || return_code=$?
        fi
        echo "PDF_DIFF_STATUS=$return_code" >> $GITHUB_ENV
      shell: bash
  
    - name: "Upload pdf diff"
      if: "${{ inputs.file-to-pdf-diff }}"
      uses: actions/upload-artifact@v1.0.0
      with:
        name: diff-output
        path: /tmp/diff-result-pdf.png

    - name: "Add pdf diff comment"
      if: "${{ inputs.file-to-pdf-diff }}"
      run: |
        if [ "$PDF_DIFF_STATUS" -eq 0 ]; then
          MESSAGE="No PDF diff."
        else
          MESSAGE="PDF diff. See artifacts for file."          
        fi

        jq -nc "{\"body\": \"$MESSAGE\"}" | \
        curl -sL  -X POST -d @- \
          -H "Content-Type: application/json" \
          -H "Authorization: token ${{ github.token }}" \
          "${{ github.event.pull_request.comments_url }}"
      shell: bash
