on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test_stdout:
    runs-on: ubuntu-latest
    name: Exercise action for stdout
    steps:
      - uses: actions/checkout@v3
      - id: diff
        uses: ./
        with:
          file-to-execute: ".github/workflows/test_stdout.sh"
          files-to-clobber: ".github/workflows/test_stdout.sh"

  test_image:
    runs-on: ubuntu-latest
    name: Exercise action for image
    steps:
      - uses: actions/checkout@v3
      - id: diff
        uses: ./
        with:
          file-to-execute: ".github/workflows/test_image.sh"
          files-to-clobber: ".github/workflows/test_image.sh"
          file-to-image-diff: "/tmp/branch.png"
